# Generated by Django 3.1.4 on 2020-12-30 10:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meme_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meme',
            old_name='downvotes',
            new_name='views',
        ),
        migrations.RemoveField(
            model_name='meme',
            name='upvotes',
        ),
        migrations.AddField(
            model_name='meme',
            name='private',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='meme',
            name='image_string',
            field=models.CharField(default='', max_length=9999999999999999999),
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('upvote', models.BooleanField(default=False)),
                ('meme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meme_vote', to='meme_api.meme')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vote', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('text', models.CharField(default='', max_length=9999999999)),
                ('meme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meme_comment', to='meme_api.meme')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
