# Generated by Django 3.1.4 on 2021-02-21 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meme_api', '0002_auto_20201230_1016'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='')),
            ],
            options={
                'verbose_name_plural': 'Videos',
            },
        ),
    ]
