# Generated by Django 3.1.4 on 2021-02-21 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meme_api', '0003_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='meme',
            name='vide',
            field=models.BooleanField(default=False),
        ),
    ]
