# Generated by Django 3.1.4 on 2021-02-21 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meme_api', '0004_meme_vide'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meme',
            old_name='vide',
            new_name='video',
        ),
    ]
