# Generated by Django 3.1.4 on 2021-02-21 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meme_api', '0005_auto_20210221_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meme',
            name='video',
            field=models.IntegerField(default=0),
        ),
    ]
