
name: Angular Test


on:
    push:
      branches: [ main ]
    pull_request:
      branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - uses: actions/checkout@v2
      - name: Angular Full CI
        uses: colbyhill21/angular-full-ci/@v1.0
        with:
          testcommand: run test:ci
          working-directory: ./frontend
